# Generated by Django 2.1.7 on 2019-03-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_image', models.ImageField(default='default_food.jpg', upload_to='food_cat_images')),
                ('category_short_description', models.CharField(max_length=250)),
                ('category_long_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FoodInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_image', models.ImageField(default='default_food.jpg', upload_to='food_cat_images')),
                ('food_short_info', models.CharField(max_length=250)),
                ('food_long_description', models.CharField(max_length=500)),
                ('food_love', models.IntegerField(null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodCategory')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
